### PR TITLE
Support cases when one file may be in multiple packages

### PR DESCRIPTION
**Pull request by tempora-mutantur**
Hello.

There is a tool called Coverlet which is a .NET utility that collects
code coverage information and it produces reports in Cobertura. And this
Coberura report may contain one file in different packages
(.NET assemblies). .NET allows you to reference one file in multiple
projects(assemblies). Because of this, when you use the Cobertura plugin
to publish your code coverage in Jenkins it shows it incorrect because
the plugin uses Muenchian grouping which doesn't allow you to have
one file in multiple packages, it just groups them, globally for a whole
report. Changed the xslt scheme to use the for-each-group which allows
to have one file in multiple packages.

Thank you.

### CODE REVIEW

**Comment by jeffpearce** [comment]
Thanks for the pr. Can you give me an example to better understand? Say you have an assembly with file A and B, and a second assembly with file A and C. What does the coverage report looks like now, and how do you expect it to look?

**Comment by tempora-mutantur** [comment]
@jeffpearce 
Hi.
In this case, before this change, the file A after our processing with Code Coverage API would be only in the first assembly and it would have information for the file A from the Assembly2. It will swallow coverage for this file from the first assembly because of grouping by filename. We want to save the coverage for this file for all assemblies that it's used in and we want to have the same kinda structure as we have in our Cobertura report and we want this file to be in both assemblies.

Cobertura:
    Assembly1
        File A
        File B
    Assembly2
        File A
        File C

Was:
    Assembly1
        File A from Assembly2
        File B
    Assembly2
        File C

Would be
    Assembly1
        File A
        File B
    Assembly2
        File A
        File C

Thank you

**Comment by cizezsy** [comment]
@jeffpearce The current method of grouping is Muenchian grouping which will group classes by its filename globally. So if one class in package 'X' have filename 'A'  and another class in Package 'Y' have filename 'A'. The class in package 'Y' will be moved to package 'X'. 

This PR uses XSLT 2.0 `for-each-group` which will only group classes in the same package.

**Comment by jeffpearce** [comment]
Hi @cizezsy . My only concern was whether this might break other languages such as Java or javascript, and I hadn't time to think about it. This seems like it would still do the right thing though

**Comment by jeffpearce** [comment]
@cizezsy - do you want to do a release?

**Comment by cizezsy** [comment]
@jeffpearce Could you also check [# 114](https://github.com/jenkinsci/cobertura-plugin/pull/114/files)? I think we can release a new version after this PR merged. thanks!

**Comment by tempora-mutantur** [comment]
@jeffmaury 
Hi.

Could you, please, answer on the Shenyu's request?
Would really want to have this PR's change released.

Thank you.

**Comment by casz** [comment]
Would be nice with a release 😅

**Pull request merged**
