### PR TITLE
Expose coverage targets

### PR DESCRIPTION
**Pull request by jeffpearce**
Addresses #67 by exposing coverage target for pipeline builds. For example, to set line coverage targets:
```
    step([$class: 'CoberturaPublisher',
          coberturaReportFile: '**/coverage.xml',
          failUnhealthy: true,
          failUnstable: true,
          lineCoverageTargets: '90.0, 80.1, 50'])
```

The meaning of each number in the lineCoverageTargets is the same as available in the non-pipeline UI, in this case:
* Report health as 100% if line coverage > 90%
* Report health as 0% if line coverage < 80.1%
* Mark build as unstable if line coverage < 50%

In addition to lineCoverageTargets, you can specify the following properties:
* packageCoverageTargets
* fileCoverageTargets
* classCoverageTargets
* methodCoverageTargets
* conditionalCoverageTargets

### CODE REVIEW

**Comment by jeffpearce** [comment]
@mbarrien or @schristou - any chance you could look at this? The recent pipeline update doesn't support coverage targets.

**Comment by JorisAndrade** [comment]
Any news on this ?

**Comment by amalsgit** [comment]
Hi, Any update on this? Badly missing coverage metric targets in the cobertura pipeline script.

**Comment by j03m** [comment]
Ditto +1 for this

**Comment by stefangoor** [comment]
+1 would really help to have this

**Comment by echatman** [comment]
+1 we need this too, will someone please merge this pull request?

**Comment by christ66** [comment]
I'm fine with these changes, and with merging this PR.

 For future please make sure to disable whitespace altering done by your IDE. There are about 200 line adds because of whitespace changes. See [PR with whitespaces](https://github.com/jenkinsci/cobertura-plugin/pull/68/files) vs [PR with no whitespace changes](https://github.com/jenkinsci/cobertura-plugin/pull/68/files?w=1). Example: `CoberturaPublisherPipelineTest.java` converts spaces to tabs.

**Comment by stefangoor** [comment]
Great to hear this was merged, looking forward to having that feature 👍 

Is there a release planned soon?

Thanks

**Comment by tjallingran** [comment]
Great to see that this has been implemented and that this issue provides examples and syntax info. Are there plans to document the syntax somewhere and / or to support the syntax in the Pipeline Script Snippet Generator (#70)?

**Comment by jeffpearce** [comment]
I prefer that the snippet generator needs to support this before it's merged. Someone needs to figure out how though - the coverage targets are more complicated fields, so you don't get them for free like the other fields.

**Comment by tjallingran** [comment]
Makes sense, thanks for the reply. I checked internally this morning, but it wouldn't be a priority for us to work on this.

By the way, for some reason version 1.11 already has a usable snippet generator. The coverage targets are of course ignored (i.e. they don't affect the generated snippets), but other than that, it works (tested with Jenkins 2.60.2).

**Comment by esmaras** [comment]
Any documentation on this would be nice. I had to search for a few hours before finding this and even still it is not in the snippet generator in Jenkins. A lot of people are probably missing these wonderful additions!

**Comment by Czar-Ec** [comment]
Is there any documentation/resources where this information is provided?

**Comment by jeffpearce** [comment]
This should all be documented in the snippet generator if you check the "Advanced" option.

**Pull request merged**
