### PR TITLE
[FIXED JENKINS-26410] Dashboard links broken when inside folder

### PR DESCRIPTION
**Pull request by olivergondza**
Fix [JENKINS-26410](https://issues.jenkins-ci.org/browse/JENKINS-26410).

### CODE REVIEW

**Comment by olivergondza** [comment]
@uhafner, @Tamini, as most recent contributors, any objections against rising core dependency to 1.480.3?

**Comment by uhafner** [comment]
No, go ahead. I just fixed a similar issue with broken column links.

**Comment by KostyaSha** [comment]
Why not released if you merged fixes?

**Comment by olivergondza** [comment]
@KostyaSha: no particular reason, releasing 1.9.7 now.

**Pull request merged**
