### PR TITLE
[JENKINS-6684] Cobertura plugin should autoconfigure for Maven projects

### PR DESCRIPTION
**Pull request by dennisl**
Here is a fix for https://issues.jenkins-ci.org/browse/JENKINS-6684

### CODE REVIEW

**Comment by KostyaSha** [comment]
This doesn't look like autoconfigure of maven job, for maven-plugin integration you need define special publisher AFAIR, then it will have no UI options and will use hardcoded values. junit-plugin can be as example.

**Comment by dennisl** [comment]
It is not autoconfigure in the sense that it looks into the POM of the Maven project, to find the correct value.

What my pull request does, and what  the original poster wants (see JIRA issue) is for the Jenkins plugin to supply a reasonable default value.

**Comment by KostyaSha** [comment]
Then name commit accordingly "Provide default value"

**Comment by dennisl** [comment]
I'm accustomed to always use the title of the issue for the commit message. And since I was not the one  who reported the issue I didn't want to change the title of the issue. Feel free to change the title to something more appropriate if you want to. I just want to get my pull request merged and a release made.

**Comment by jeffpearce** [comment]
This predates my time as maintainer, but I'd like to close or merge old PRs. It seems like it shouldn't break any existing jobs, so I'm inclined to merge it if you are willing to resolve the conflicts.

**Pull request closed without merging**
